# Generated by Django 3.2.4 on 2021-06-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_curso', models.TextField()),
                ('descripcion', models.TextField()),
                ('duracion', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=15)),
                ('costo', models.FloatField()),
                ('estado', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
