# Generated by Django 3.2.4 on 2021-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_consultacurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultacurso',
            name='update',
        ),
        migrations.AlterField(
            model_name='consultacurso',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado'),
        ),
    ]
