# Generated by Django 3.2.4 on 2021-08-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_auto_20210806_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultaCurso',
        ),
    ]
