# Generated by Django 3.2.4 on 2021-08-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_consultacurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultaCurso',
        ),
    ]
