# Generated by Django 3.2.4 on 2021-08-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_consultacurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultacurso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='consultacurso',
            name='imagen',
        ),
    ]
