# Generated by Django 3.2.4 on 2021-08-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_consultacurso_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultacurso',
            name='imagen',
        ),
    ]
