# Generated by Django 3.2.4 on 2021-08-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_remove_consultacurso_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultacurso',
            options={'ordering': ['-created'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
