# Generated by Django 3.2.4 on 2021-08-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_alter_consultacurso_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultaCurso',
        ),
    ]
