# Generated by Django 3.2.4 on 2021-08-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_alter_cursos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.FileField(null=True, upload_to='fotos/', verbose_name='Fotografía'),
        ),
    ]
