# Generated by Django 3.2.4 on 2021-08-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0023_alter_cursos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
